# RawData处理

In [1]:
import pandas as pd
import numpy as np

In [2]:
filename = 'leguan_test2_Rec 29.tsv'
data1 = pd.read_csv(filename,sep='\t')

In [3]:
data2 = data1.drop(['GazeEventType','RecordingName','RecordingDate','FixationFilter','RecordingTimestamp'],axis='columns')
index1 = data2['MediaName'].dropna().index
print(index1)#非空名的index

Int64Index([  624,   625,   626,   627,   628,   629,   630,   631,   632,
              633,
            ...
            29381, 29382, 29383, 29384, 29385, 29386, 29387, 29388, 29389,
            29390],
           dtype='int64', length=27336)

In [4]:
index1 = data2['MediaName'].dropna().index
print(index1)#非空名的index

Int64Index([  624,   625,   626,   627,   628,   629,   630,   631,   632,
              633,
            ...
            29381, 29382, 29383, 29384, 29385, 29386, 29387, 29388, 29389,
            29390],
           dtype='int64', length=27336)

In [5]:
data3 = data2[data2.index.isin(index1)]
data3.head()

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,AOI[Rectangle]Hit,AOI[Rectangle 2]Hit,AOI[Rectangle]Hit.1,AOI[Rectangle 2]Hit.1,AOI[Rectangle]Hit.2,AOI[Rectangle 2]Hit.2,...,AOI[Rectangle 2]Hit.84,AOI[Rectangle]Hit.85,AOI[Rectangle 2]Hit.85,AOI[Rectangle]Hit.86,AOI[Rectangle 2]Hit.86,AOI[Rectangle]Hit.87,AOI[Rectangle 2]Hit.87,AOI[Rectangle]Hit.88,AOI[Rectangle 2]Hit.88,Unnamed: 187
624,WGT_BLOCK4,test2,fixation.jpg,297.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
625,WGT_BLOCK4,test2,fixation.jpg,297.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
626,WGT_BLOCK4,test2,fixation.jpg,297.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
627,WGT_BLOCK4,test2,fixation.jpg,297.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
628,WGT_BLOCK4,test2,fixation.jpg,297.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data3.tail()

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,AOI[Rectangle]Hit,AOI[Rectangle 2]Hit,AOI[Rectangle]Hit.1,AOI[Rectangle 2]Hit.1,AOI[Rectangle]Hit.2,AOI[Rectangle 2]Hit.2,...,AOI[Rectangle 2]Hit.84,AOI[Rectangle]Hit.85,AOI[Rectangle 2]Hit.85,AOI[Rectangle]Hit.86,AOI[Rectangle 2]Hit.86,AOI[Rectangle]Hit.87,AOI[Rectangle 2]Hit.87,AOI[Rectangle]Hit.88,AOI[Rectangle 2]Hit.88,Unnamed: 187
29386,WGT_BLOCK4,test2,00-10.jpg,427.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29387,WGT_BLOCK4,test2,00-10.jpg,427.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29388,WGT_BLOCK4,test2,00-10.jpg,427.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29389,WGT_BLOCK4,test2,00-10.jpg,427.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29390,WGT_BLOCK4,test2,00-10.jpg,427.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
index2 = data3[data3['MediaName']=='fixation.jpg'].index
data4 = data3[~data3.index.isin(index2)]
data4.head() #删除多余图片刺激

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,AOI[Rectangle]Hit,AOI[Rectangle 2]Hit,AOI[Rectangle]Hit.1,AOI[Rectangle 2]Hit.1,AOI[Rectangle]Hit.2,AOI[Rectangle 2]Hit.2,...,AOI[Rectangle 2]Hit.84,AOI[Rectangle]Hit.85,AOI[Rectangle 2]Hit.85,AOI[Rectangle]Hit.86,AOI[Rectangle 2]Hit.86,AOI[Rectangle]Hit.87,AOI[Rectangle 2]Hit.87,AOI[Rectangle]Hit.88,AOI[Rectangle 2]Hit.88,Unnamed: 187
950,WGT_BLOCK4,test2,01-10.jpg,533.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
951,WGT_BLOCK4,test2,01-10.jpg,533.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
952,WGT_BLOCK4,test2,01-10.jpg,533.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
953,WGT_BLOCK4,test2,01-10.jpg,533.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
954,WGT_BLOCK4,test2,01-10.jpg,533.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 一、01-00组合数据预处理

In [8]:
group0100 = data4[data4['MediaName']=='01-00.jpg']  #0100组合数据
group0100.head()

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,AOI[Rectangle]Hit,AOI[Rectangle 2]Hit,AOI[Rectangle]Hit.1,AOI[Rectangle 2]Hit.1,AOI[Rectangle]Hit.2,AOI[Rectangle 2]Hit.2,...,AOI[Rectangle 2]Hit.84,AOI[Rectangle]Hit.85,AOI[Rectangle 2]Hit.85,AOI[Rectangle]Hit.86,AOI[Rectangle 2]Hit.86,AOI[Rectangle]Hit.87,AOI[Rectangle 2]Hit.87,AOI[Rectangle]Hit.88,AOI[Rectangle 2]Hit.88,Unnamed: 187
2858,WGT_BLOCK4,test2,01-00.jpg,947.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2859,WGT_BLOCK4,test2,01-00.jpg,947.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2860,WGT_BLOCK4,test2,01-00.jpg,947.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861,WGT_BLOCK4,test2,01-00.jpg,947.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2862,WGT_BLOCK4,test2,01-00.jpg,947.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
group0100 = group0100.dropna(how='all',axis = 'columns')
group0100.head()     #删除竖排缺省值

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,AOI[Rectangle]Hit.30,AOI[Rectangle 2]Hit.30,AOI[Rectangle]Hit.36,AOI[Rectangle 2]Hit.36,AOI[Rectangle]Hit.42,AOI[Rectangle 2]Hit.42,AOI[Rectangle]Hit.54,AOI[Rectangle 2]Hit.54,AOI[Rectangle]Hit.55,AOI[Rectangle 2]Hit.55
2858,WGT_BLOCK4,test2,01-00.jpg,947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2859,WGT_BLOCK4,test2,01-00.jpg,947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2860,WGT_BLOCK4,test2,01-00.jpg,947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2861,WGT_BLOCK4,test2,01-00.jpg,947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2862,WGT_BLOCK4,test2,01-00.jpg,947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [10]:
group0100 = group0100.rename(columns={'AOI[Rectangle]Hit.30': 'left1','AOI[Rectangle 2]Hit.30': 'right1'})
group0100 = group0100.rename(columns={'AOI[Rectangle]Hit.36': 'left2','AOI[Rectangle 2]Hit.36': 'right2'})
group0100 = group0100.rename(columns={'AOI[Rectangle]Hit.42': 'left3','AOI[Rectangle 2]Hit.42': 'right3'})
group0100 = group0100.rename(columns={'AOI[Rectangle]Hit.54': 'left4','AOI[Rectangle 2]Hit.54': 'right4'})
group0100 = group0100.rename(columns={'AOI[Rectangle]Hit.55': 'left5','AOI[Rectangle 2]Hit.55': 'right5'})
group0100.head()    #修改列标

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,left1,right1,left2,right2,left3,right3,left4,right4,left5,right5
2858,WGT_BLOCK4,test2,01-00.jpg,947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2859,WGT_BLOCK4,test2,01-00.jpg,947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2860,WGT_BLOCK4,test2,01-00.jpg,947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2861,WGT_BLOCK4,test2,01-00.jpg,947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2862,WGT_BLOCK4,test2,01-00.jpg,947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [11]:
group0100 = group0100.drop_duplicates()
group0100

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,left1,right1,left2,right2,left3,right3,left4,right4,left5,right5
2858,WGT_BLOCK4,test2,01-00.jpg,947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2915,WGT_BLOCK4,test2,01-00.jpg,197.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
2974,WGT_BLOCK4,test2,01-00.jpg,350.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
3079,WGT_BLOCK4,test2,01-00.jpg,320.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
3175,WGT_BLOCK4,test2,01-00.jpg,377.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
3288,WGT_BLOCK4,test2,01-00.jpg,513.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
3442,WGT_BLOCK4,test2,01-00.jpg,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
17249,WGT_BLOCK4,test2,01-00.jpg,3117.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
17376,WGT_BLOCK4,test2,01-00.jpg,190.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
17433,WGT_BLOCK4,test2,01-00.jpg,107.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
17465,WGT_BLOCK4,test2,01-00.jpg,150.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
17510,WGT_BLOCK4,test2,01-00.jpg,380.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
17624,WGT_BLOCK4,test2,01-00.jpg,423.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
17751,WGT_BLOCK4,test2,01-00.jpg,333.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
17851,WGT_BLOCK4,test2,01-00.jpg,697.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
18215,WGT_BLOCK4,test2,01-00.jpg,220.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18280,WGT_BLOCK4,test2,01-00.jpg,263.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18359,WGT_BLOCK4,test2,01-00.jpg,303.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18450,WGT_BLOCK4,test2,01-00.jpg,20.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18456,WGT_BLOCK4,test2,01-00.jpg,243.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18529,WGT_BLOCK4,test2,01-00.jpg,130.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18568,WGT_BLOCK4,test2,01-00.jpg,293.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18656,WGT_BLOCK4,test2,01-00.jpg,587.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22044,WGT_BLOCK4,test2,01-00.jpg,1067.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
22101,WGT_BLOCK4,test2,01-00.jpg,130.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
22140,WGT_BLOCK4,test2,01-00.jpg,80.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
22164,WGT_BLOCK4,test2,01-00.jpg,27.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
22172,WGT_BLOCK4,test2,01-00.jpg,107.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
22204,WGT_BLOCK4,test2,01-00.jpg,370.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN
22315,WGT_BLOCK4,test2,01-00.jpg,360.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN
22423,WGT_BLOCK4,test2,01-00.jpg,1057.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
23941,WGT_BLOCK4,test2,01-00.jpg,1113.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
24012,WGT_BLOCK4,test2,01-00.jpg,300.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN
24102,WGT_BLOCK4,test2,01-00.jpg,453.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN
24238,WGT_BLOCK4,test2,01-00.jpg,67.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN
24258,WGT_BLOCK4,test2,01-00.jpg,377.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN
24371,WGT_BLOCK4,test2,01-00.jpg,900.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN

# 二、01-10组合数据预处理  (0110)

In [12]:
group0101 = data4[data4['MediaName']=='01-10.jpg']  #0100组合数据
group0101 = group0101.dropna(how='all',axis = 'columns')  #删除竖排缺省值
group0101.head()

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,AOI[Rectangle]Hit.32,AOI[Rectangle 2]Hit.32,AOI[Rectangle]Hit.37,AOI[Rectangle 2]Hit.37,AOI[Rectangle]Hit.40,AOI[Rectangle 2]Hit.40,AOI[Rectangle]Hit.50,AOI[Rectangle 2]Hit.50,AOI[Rectangle]Hit.59,AOI[Rectangle 2]Hit.59
950,WGT_BLOCK4,test2,01-10.jpg,533.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
951,WGT_BLOCK4,test2,01-10.jpg,533.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
952,WGT_BLOCK4,test2,01-10.jpg,533.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
953,WGT_BLOCK4,test2,01-10.jpg,533.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
954,WGT_BLOCK4,test2,01-10.jpg,533.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [13]:
group0101 = group0101.rename(columns={'AOI[Rectangle]Hit.32': 'left1','AOI[Rectangle 2]Hit.32': 'right1'})
group0101 = group0101.rename(columns={'AOI[Rectangle]Hit.37': 'left2','AOI[Rectangle 2]Hit.37': 'right2'})
group0101 = group0101.rename(columns={'AOI[Rectangle]Hit.40': 'left3','AOI[Rectangle 2]Hit.40': 'right3'})
group0101 = group0101.rename(columns={'AOI[Rectangle]Hit.50': 'left4','AOI[Rectangle 2]Hit.50': 'right4'})
group0101 = group0101.rename(columns={'AOI[Rectangle]Hit.59': 'left5','AOI[Rectangle 2]Hit.59': 'right5'})
group0101.head()    #修改列标

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,left1,right1,left2,right2,left3,right3,left4,right4,left5,right5
950,WGT_BLOCK4,test2,01-10.jpg,533.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
951,WGT_BLOCK4,test2,01-10.jpg,533.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
952,WGT_BLOCK4,test2,01-10.jpg,533.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
953,WGT_BLOCK4,test2,01-10.jpg,533.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
954,WGT_BLOCK4,test2,01-10.jpg,533.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [14]:
group0101 = group0101.drop_duplicates()
group0101

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,left1,right1,left2,right2,left3,right3,left4,right4,left5,right5
950,WGT_BLOCK4,test2,01-10.jpg,533.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
1037,WGT_BLOCK4,test2,01-10.jpg,257.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
1114,WGT_BLOCK4,test2,01-10.jpg,307.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
1206,WGT_BLOCK4,test2,01-10.jpg,140.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
1248,WGT_BLOCK4,test2,01-10.jpg,207.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
1310,WGT_BLOCK4,test2,01-10.jpg,380.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
1424,WGT_BLOCK4,test2,01-10.jpg,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
1430,WGT_BLOCK4,test2,01-10.jpg,463.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
4780,WGT_BLOCK4,test2,01-10.jpg,1167.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
4867,WGT_BLOCK4,test2,01-10.jpg,167.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN
4917,WGT_BLOCK4,test2,01-10.jpg,110.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN
4950,WGT_BLOCK4,test2,01-10.jpg,180.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN
5004,WGT_BLOCK4,test2,01-10.jpg,467.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN
5144,WGT_BLOCK4,test2,01-10.jpg,413.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN
5268,WGT_BLOCK4,test2,01-10.jpg,693.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN
15327,WGT_BLOCK4,test2,01-10.jpg,2213.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
15880,WGT_BLOCK4,test2,01-10.jpg,763.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
24922,WGT_BLOCK4,test2,01-10.jpg,307.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24996,WGT_BLOCK4,test2,01-10.jpg,450.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25131,WGT_BLOCK4,test2,01-10.jpg,510.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25284,WGT_BLOCK4,test2,01-10.jpg,416.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25409,WGT_BLOCK4,test2,01-10.jpg,637.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27840,WGT_BLOCK4,test2,01-10.jpg,1353.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
27942,WGT_BLOCK4,test2,01-10.jpg,157.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
27989,WGT_BLOCK4,test2,01-10.jpg,437.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
28120,WGT_BLOCK4,test2,01-10.jpg,20.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
28126,WGT_BLOCK4,test2,01-10.jpg,280.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
28210,WGT_BLOCK4,test2,01-10.jpg,260.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
28288,WGT_BLOCK4,test2,01-10.jpg,483.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
28433,WGT_BLOCK4,test2,01-10.jpg,320.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN

# 三、00-01组合数据预处理

In [15]:
group0001 = data4[data4['MediaName']=='00-01.jpg']  #0100组合数据
group0001 = group0001.dropna(how='all',axis = 'columns')  #删除竖排缺省值
group0001.head()

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,AOI[Rectangle]Hit.35,AOI[Rectangle 2]Hit.35,AOI[Rectangle]Hit.38,AOI[Rectangle 2]Hit.38,AOI[Rectangle]Hit.49,AOI[Rectangle 2]Hit.49,AOI[Rectangle]Hit.52,AOI[Rectangle 2]Hit.52,AOI[Rectangle]Hit.56,AOI[Rectangle 2]Hit.56
1907,WGT_BLOCK4,test2,00-01.jpg,963.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
1908,WGT_BLOCK4,test2,00-01.jpg,963.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
1909,WGT_BLOCK4,test2,00-01.jpg,963.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
1910,WGT_BLOCK4,test2,00-01.jpg,963.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
1911,WGT_BLOCK4,test2,00-01.jpg,963.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN

In [16]:
group0001 = group0001.rename(columns={'AOI[Rectangle]Hit.35': 'left1','AOI[Rectangle 2]Hit.35': 'right1'})
group0001 = group0001.rename(columns={'AOI[Rectangle]Hit.38': 'left2','AOI[Rectangle 2]Hit.38': 'right2'})
group0001 = group0001.rename(columns={'AOI[Rectangle]Hit.59': 'left3','AOI[Rectangle 2]Hit.49': 'right3'})
group0001 = group0001.rename(columns={'AOI[Rectangle]Hit.52': 'left4','AOI[Rectangle 2]Hit.52': 'right4'})
group0001 = group0001.rename(columns={'AOI[Rectangle]Hit.56': 'left5','AOI[Rectangle 2]Hit.56': 'right5'})
group0001.head()

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,left1,right1,left2,right2,AOI[Rectangle]Hit.49,right3,left4,right4,left5,right5
1907,WGT_BLOCK4,test2,00-01.jpg,963.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
1908,WGT_BLOCK4,test2,00-01.jpg,963.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
1909,WGT_BLOCK4,test2,00-01.jpg,963.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
1910,WGT_BLOCK4,test2,00-01.jpg,963.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
1911,WGT_BLOCK4,test2,00-01.jpg,963.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN

In [17]:
group0001 = group0001.drop_duplicates()
group0001

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,left1,right1,left2,right2,AOI[Rectangle]Hit.49,right3,left4,right4,left5,right5
1907,WGT_BLOCK4,test2,00-01.jpg,963.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
1950,WGT_BLOCK4,test2,00-01.jpg,30.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
1959,WGT_BLOCK4,test2,00-01.jpg,43.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN
1972,WGT_BLOCK4,test2,00-01.jpg,100.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN
2002,WGT_BLOCK4,test2,00-01.jpg,180.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN
2056,WGT_BLOCK4,test2,00-01.jpg,390.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
2173,WGT_BLOCK4,test2,00-01.jpg,20.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
2179,WGT_BLOCK4,test2,00-01.jpg,527.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
2337,WGT_BLOCK4,test2,00-01.jpg,557.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
2504,WGT_BLOCK4,test2,00-01.jpg,30.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
7653,WGT_BLOCK4,test2,00-01.jpg,1006.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7728,WGT_BLOCK4,test2,00-01.jpg,167.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
7778,WGT_BLOCK4,test2,00-01.jpg,20.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
7784,WGT_BLOCK4,test2,00-01.jpg,257.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7861,WGT_BLOCK4,test2,00-01.jpg,250.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7936,WGT_BLOCK4,test2,00-01.jpg,20.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7942,WGT_BLOCK4,test2,00-01.jpg,393.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
8060,WGT_BLOCK4,test2,00-01.jpg,367.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
8170,WGT_BLOCK4,test2,00-01.jpg,590.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
9570,WGT_BLOCK4,test2,00-01.jpg,1306.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9701,WGT_BLOCK4,test2,00-01.jpg,1920.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13424,WGT_BLOCK4,test2,00-01.jpg,1760.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
13538,WGT_BLOCK4,test2,00-01.jpg,2380.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN
21088,WGT_BLOCK4,test2,00-01.jpg,640.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
21149,WGT_BLOCK4,test2,00-01.jpg,313.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
21243,WGT_BLOCK4,test2,00-01.jpg,510.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
21396,WGT_BLOCK4,test2,00-01.jpg,63.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
21415,WGT_BLOCK4,test2,00-01.jpg,440.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
21547,WGT_BLOCK4,test2,00-01.jpg,627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0

# 四、00-10组合数据预处理

In [18]:
group0010 = data4[data4['MediaName']=='00-10.jpg']  #0100组合数据
group0010 = group0010.dropna(how='all',axis = 'columns')  #删除竖排缺省值
group0010.head()

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,AOI[Rectangle]Hit.34,AOI[Rectangle 2]Hit.34,AOI[Rectangle]Hit.41,AOI[Rectangle 2]Hit.41,AOI[Rectangle]Hit.46,AOI[Rectangle 2]Hit.46,AOI[Rectangle]Hit.48,AOI[Rectangle 2]Hit.48,AOI[Rectangle]Hit.57,AOI[Rectangle 2]Hit.57
8614,WGT_BLOCK4,test2,00-10.jpg,1017.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8615,WGT_BLOCK4,test2,00-10.jpg,1017.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8616,WGT_BLOCK4,test2,00-10.jpg,1017.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8617,WGT_BLOCK4,test2,00-10.jpg,1017.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8618,WGT_BLOCK4,test2,00-10.jpg,1017.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
group0010 = group0010.rename(columns={'AOI[Rectangle]Hit.34': 'left1','AOI[Rectangle 2]Hit.34': 'right1'})
group0010 = group0010.rename(columns={'AOI[Rectangle]Hit.41': 'left2','AOI[Rectangle 2]Hit.41': 'right2'})
group0010 = group0010.rename(columns={'AOI[Rectangle]Hit.46': 'left3','AOI[Rectangle 2]Hit.46': 'right3'})
group0010 = group0010.rename(columns={'AOI[Rectangle]Hit.48': 'left4','AOI[Rectangle 2]Hit.48': 'right4'})
group0010 = group0010.rename(columns={'AOI[Rectangle]Hit.57': 'left5','AOI[Rectangle 2]Hit.57': 'right5'})
group0010.head()

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,left1,right1,left2,right2,left3,right3,left4,right4,left5,right5
8614,WGT_BLOCK4,test2,00-10.jpg,1017.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8615,WGT_BLOCK4,test2,00-10.jpg,1017.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8616,WGT_BLOCK4,test2,00-10.jpg,1017.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8617,WGT_BLOCK4,test2,00-10.jpg,1017.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8618,WGT_BLOCK4,test2,00-10.jpg,1017.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
group0010 = group0010.drop_duplicates()
group0010

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,left1,right1,left2,right2,left3,right3,left4,right4,left5,right5
8614,WGT_BLOCK4,test2,00-10.jpg,1017.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8692,WGT_BLOCK4,test2,00-10.jpg,223.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8759,WGT_BLOCK4,test2,00-10.jpg,537.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8920,WGT_BLOCK4,test2,00-10.jpg,110.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8953,WGT_BLOCK4,test2,00-10.jpg,443.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9086,WGT_BLOCK4,test2,00-10.jpg,743.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12478,WGT_BLOCK4,test2,00-10.jpg,1220.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
12581,WGT_BLOCK4,test2,00-10.jpg,207.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN
12643,WGT_BLOCK4,test2,00-10.jpg,53.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN
12659,WGT_BLOCK4,test2,00-10.jpg,23.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN
12666,WGT_BLOCK4,test2,00-10.jpg,597.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN
12845,WGT_BLOCK4,test2,00-10.jpg,373.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN
12957,WGT_BLOCK4,test2,00-10.jpg,177.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
13010,WGT_BLOCK4,test2,00-10.jpg,1760.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
14380,WGT_BLOCK4,test2,00-10.jpg,2156.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
14899,WGT_BLOCK4,test2,00-10.jpg,927.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
26834,WGT_BLOCK4,test2,00-10.jpg,980.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
26906,WGT_BLOCK4,test2,00-10.jpg,257.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
26983,WGT_BLOCK4,test2,00-10.jpg,387.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
27099,WGT_BLOCK4,test2,00-10.jpg,503.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
27250,WGT_BLOCK4,test2,00-10.jpg,270.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
27331,WGT_BLOCK4,test2,00-10.jpg,143.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
27374,WGT_BLOCK4,test2,00-10.jpg,540.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
28796,WGT_BLOCK4,test2,00-10.jpg,333.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
28820,WGT_BLOCK4,test2,00-10.jpg,260.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
28898,WGT_BLOCK4,test2,00-10.jpg,173.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN
28950,WGT_BLOCK4,test2,00-10.jpg,427.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
29078,WGT_BLOCK4,test2,00-10.jpg,43.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN
29091,WGT_BLOCK4,test2,00-10.jpg,257.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN
29168,WGT_BLOCK4,test2,00-10.jpg,200.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
29228,WGT_BLOCK4,test2,00-10.jpg,383.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN

# 五、10-00组合数据预处理

In [21]:
group1000 = data4[data4['MediaName']=='10-00.jpg']  #1000组合数据
group1000 = group1000.dropna(how='all',axis = 'columns')  #删除竖排缺省值
group1000.head()

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,AOI[Rectangle]Hit.44,AOI[Rectangle 2]Hit.44,AOI[Rectangle]Hit.45,AOI[Rectangle 2]Hit.45,AOI[Rectangle]Hit.47,AOI[Rectangle 2]Hit.47,AOI[Rectangle]Hit.53,AOI[Rectangle 2]Hit.53,AOI[Rectangle]Hit.58,AOI[Rectangle 2]Hit.58
10546,WGT_BLOCK4,test2,10-00.jpg,1057.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
10547,WGT_BLOCK4,test2,10-00.jpg,1057.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
10548,WGT_BLOCK4,test2,10-00.jpg,1057.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
10549,WGT_BLOCK4,test2,10-00.jpg,1057.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
10550,WGT_BLOCK4,test2,10-00.jpg,1057.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [22]:
group1000 = group1000.rename(columns={'AOI[Rectangle]Hit.44': 'left1','AOI[Rectangle 2]Hit.44': 'right1'})
group1000 = group1000.rename(columns={'AOI[Rectangle]Hit.45': 'left2','AOI[Rectangle 2]Hit.45': 'right2'})
group1000 = group1000.rename(columns={'AOI[Rectangle]Hit.47': 'left3','AOI[Rectangle 2]Hit.47': 'right3'})
group1000 = group1000.rename(columns={'AOI[Rectangle]Hit.53': 'left4','AOI[Rectangle 2]Hit.53': 'right4'})
group1000 = group1000.rename(columns={'AOI[Rectangle]Hit.58': 'left5','AOI[Rectangle 2]Hit.58': 'right5'})
group1000.head()

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,left1,right1,left2,right2,left3,right3,left4,right4,left5,right5
10546,WGT_BLOCK4,test2,10-00.jpg,1057.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
10547,WGT_BLOCK4,test2,10-00.jpg,1057.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
10548,WGT_BLOCK4,test2,10-00.jpg,1057.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
10549,WGT_BLOCK4,test2,10-00.jpg,1057.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
10550,WGT_BLOCK4,test2,10-00.jpg,1057.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [23]:
group1000 = group1000.drop_duplicates()
group1000

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,left1,right1,left2,right2,left3,right3,left4,right4,left5,right5
10546,WGT_BLOCK4,test2,10-00.jpg,1057.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
10638,WGT_BLOCK4,test2,10-00.jpg,103.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
10669,WGT_BLOCK4,test2,10-00.jpg,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
10675,WGT_BLOCK4,test2,10-00.jpg,493.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
10823,WGT_BLOCK4,test2,10-00.jpg,1410.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
19171,WGT_BLOCK4,test2,10-00.jpg,920.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
19189,WGT_BLOCK4,test2,10-00.jpg,77.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
19212,WGT_BLOCK4,test2,10-00.jpg,103.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
19243,WGT_BLOCK4,test2,10-00.jpg,173.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN
19295,WGT_BLOCK4,test2,10-00.jpg,290.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN
19382,WGT_BLOCK4,test2,10-00.jpg,356.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN
19489,WGT_BLOCK4,test2,10-00.jpg,160.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN
19537,WGT_BLOCK4,test2,10-00.jpg,1113.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN
20132,WGT_BLOCK4,test2,10-00.jpg,596.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20193,WGT_BLOCK4,test2,10-00.jpg,223.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20260,WGT_BLOCK4,test2,10-00.jpg,353.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20366,WGT_BLOCK4,test2,10-00.jpg,233.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20436,WGT_BLOCK4,test2,10-00.jpg,97.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20465,WGT_BLOCK4,test2,10-00.jpg,257.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20542,WGT_BLOCK4,test2,10-00.jpg,810.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23000,WGT_BLOCK4,test2,10-00.jpg,1087.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
23111,WGT_BLOCK4,test2,10-00.jpg,737.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
23332,WGT_BLOCK4,test2,10-00.jpg,280.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
23416,WGT_BLOCK4,test2,10-00.jpg,27.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
23432,WGT_BLOCK4,test2,10-00.jpg,483.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
23577,WGT_BLOCK4,test2,10-00.jpg,337.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
25878,WGT_BLOCK4,test2,10-00.jpg,1163.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
25949,WGT_BLOCK4,test2,10-00.jpg,233.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
26019,WGT_BLOCK4,test2,10-00.jpg,433.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN
26149,WGT_BLOCK4,test2,10-00.jpg,383.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
26264,WGT_BLOCK4,test2,10-00.jpg,113.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
26298,WGT_BLOCK4,test2,10-00.jpg,20.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
26304,WGT_BLOCK4,test2,10-00.jpg,883.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN

# 六、10-01组合数据预处理

In [24]:
group1001 = data4[data4['MediaName']=='10-01.jpg']  #1000组合数据
group1001 = group1001.dropna(how='all',axis = 'columns')  #删除竖排缺省值
group1001.head()

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,AOI[Rectangle]Hit.31,AOI[Rectangle 2]Hit.31,AOI[Rectangle]Hit.33,AOI[Rectangle 2]Hit.33,AOI[Rectangle]Hit.39,AOI[Rectangle 2]Hit.39,AOI[Rectangle]Hit.43,AOI[Rectangle 2]Hit.43,AOI[Rectangle]Hit.51,AOI[Rectangle 2]Hit.51
3824,WGT_BLOCK4,test2,10-01.jpg,1063.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3825,WGT_BLOCK4,test2,10-01.jpg,1063.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3826,WGT_BLOCK4,test2,10-01.jpg,1063.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3827,WGT_BLOCK4,test2,10-01.jpg,1063.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3828,WGT_BLOCK4,test2,10-01.jpg,1063.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [25]:
group1001 = group1001.rename(columns={'AOI[Rectangle]Hit.31': 'left1','AOI[Rectangle 2]Hit.31': 'right1'})
group1001 = group1001.rename(columns={'AOI[Rectangle]Hit.33': 'left2','AOI[Rectangle 2]Hit.33': 'right2'})
group1001 = group1001.rename(columns={'AOI[Rectangle]Hit.39': 'left3','AOI[Rectangle 2]Hit.39': 'right3'})
group1001 = group1001.rename(columns={'AOI[Rectangle]Hit.43': 'left4','AOI[Rectangle 2]Hit.43': 'right4'})
group1001 = group1001.rename(columns={'AOI[Rectangle]Hit.51': 'left5','AOI[Rectangle 2]Hit.51': 'right5'})
group1001.head()

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,left1,right1,left2,right2,left3,right3,left4,right4,left5,right5
3824,WGT_BLOCK4,test2,10-01.jpg,1063.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3825,WGT_BLOCK4,test2,10-01.jpg,1063.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3826,WGT_BLOCK4,test2,10-01.jpg,1063.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3827,WGT_BLOCK4,test2,10-01.jpg,1063.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3828,WGT_BLOCK4,test2,10-01.jpg,1063.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [26]:
group1001 = group1001.drop_duplicates()
group1001

,ParticipantName,StudioTestName,MediaName,GazeEventDuration,left1,right1,left2,right2,left3,right3,left4,right4,left5,right5
3824,WGT_BLOCK4,test2,10-01.jpg,1063.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3871,WGT_BLOCK4,test2,10-01.jpg,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3877,WGT_BLOCK4,test2,10-01.jpg,210.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3940,WGT_BLOCK4,test2,10-01.jpg,207.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
4002,WGT_BLOCK4,test2,10-01.jpg,416.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
4127,WGT_BLOCK4,test2,10-01.jpg,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
4133,WGT_BLOCK4,test2,10-01.jpg,330.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
4232,WGT_BLOCK4,test2,10-01.jpg,950.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0
5741,WGT_BLOCK4,test2,10-01.jpg,210.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
5785,WGT_BLOCK4,test2,10-01.jpg,127.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
5823,WGT_BLOCK4,test2,10-01.jpg,423.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
5950,WGT_BLOCK4,test2,10-01.jpg,370.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
6061,WGT_BLOCK4,test2,10-01.jpg,180.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
6115,WGT_BLOCK4,test2,10-01.jpg,573.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN
6287,WGT_BLOCK4,test2,10-01.jpg,143.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
6330,WGT_BLOCK4,test2,10-01.jpg,383.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN
6707,WGT_BLOCK4,test2,10-01.jpg,1083.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
6770,WGT_BLOCK4,test2,10-01.jpg,333.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN
6870,WGT_BLOCK4,test2,10-01.jpg,293.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN
6958,WGT_BLOCK4,test2,10-01.jpg,1300.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN
11507,WGT_BLOCK4,test2,10-01.jpg,1283.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11631,WGT_BLOCK4,test2,10-01.jpg,1946.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16283,WGT_BLOCK4,test2,10-01.jpg,870.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
16370,WGT_BLOCK4,test2,10-01.jpg,237.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
16441,WGT_BLOCK4,test2,10-01.jpg,3117.0,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN

# 数据列表合并 
## group0100,group0101,group0001,group0010,group1000,group1001

In [27]:
cleandata = pd.concat([group0100,group0101,group0001,group0010,group1000,group1001],sort=True)

In [28]:
cleandata

,AOI[Rectangle]Hit.49,GazeEventDuration,MediaName,ParticipantName,StudioTestName,left1,left2,left3,left4,left5,right1,right2,right3,right4,right5
2858,NaN,947.0,01-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0
2915,NaN,197.0,01-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0
2974,NaN,350.0,01-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0
3079,NaN,320.0,01-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0
3175,NaN,377.0,01-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0
3288,NaN,513.0,01-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0
3442,NaN,80.0,01-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0
17249,NaN,3117.0,01-00.jpg,WGT_BLOCK4,test2,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
17376,NaN,190.0,01-00.jpg,WGT_BLOCK4,test2,NaN,1.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
17433,NaN,107.0,01-00.jpg,WGT_BLOCK4,test2,NaN,1.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
17465,NaN,150.0,01-00.jpg,WGT_BLOCK4,test2,NaN,1.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
17510,NaN,380.0,01-00.jpg,WGT_BLOCK4,test2,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
17624,NaN,423.0,01-00.jpg,WGT_BLOCK4,test2,NaN,1.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
17751,NaN,333.0,01-00.jpg,WGT_BLOCK4,test2,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
17851,NaN,697.0,01-00.jpg,WGT_BLOCK4,test2,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
18215,NaN,220.0,01-00.jpg,WGT_BLOCK4,test2,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
18280,NaN,263.0,01-00.jpg,WGT_BLOCK4,test2,0.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
18359,NaN,303.0,01-00.jpg,WGT_BLOCK4,test2,1.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
18450,NaN,20.0,01-00.jpg,WGT_BLOCK4,test2,1.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
18456,NaN,243.0,01-00.jpg,WGT_BLOCK4,test2,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
18529,NaN,130.0,01-00.jpg,WGT_BLOCK4,test2,1.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
18568,NaN,293.0,01-00.jpg,WGT_BLOCK4,test2,0.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
18656,NaN,587.0,01-00.jpg,WGT_BLOCK4,test2,1.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
22044,NaN,1067.0,01-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
22101,NaN,130.0,01-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN
22140,NaN,80.0,01-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN
22164,NaN,27.0,01-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN
22172,NaN,107.0,01-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN
22204,NaN,370.0,01-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0,NaN
22315,NaN,360.0,01-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26019,NaN,433.0,10-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0,NaN
26149,NaN,383.0,10-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN
26264,NaN,113.0,10-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN
26298,NaN,20.0,10-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN
26304,NaN,883.0,10-00.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN
3824,NaN,1063.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0
3871,NaN,20.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0
3877,NaN,210.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0
3940,NaN,207.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0
4002,NaN,416.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0
4127,NaN,20.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0
4133,NaN,330.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0
4232,NaN,950.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0
5741,NaN,210.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
5785,NaN,127.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
5823,NaN,423.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN
5950,NaN,370.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN
6061,NaN,180.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
6115,NaN,573.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0,NaN
6287,NaN,143.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN
6330,NaN,383.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN
6707,NaN,1083.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN
6770,NaN,333.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN
6870,NaN,293.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN
6958,NaN,1300.0,10-01.jpg,WGT_BLOCK4,test2,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN
11507,NaN,1283.0,10-01.jpg,WGT_BLOCK4,test2,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
11631,NaN,1946.0,10-01.jpg,WGT_BLOCK4,test2,0.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
16283,NaN,870.0,10-01.jpg,WGT_BLOCK4,test2,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
16370,NaN,237.0,10-01.jpg,WGT_BLOCK4,test2,NaN,1.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
16441,NaN,3117.0,10-01.jpg,WGT_BLOCK4,test2,NaN,0.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN

In [29]:
#cleandata.to_csv('cleandata\HYX\BLOCK2.csv')

In [30]:
name = cleandata['ParticipantName']
savefilename = name.values[1]
savefilename = savefilename +'.csv'
savefilename

'WGT_BLOCK4.csv'

In [31]:
cleandata.to_csv(savefilename)